[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "grocery-shopper"
version = "1.0"
dependencies = [
    'PyYAML'
]

[tool.setuptools.packages.find]
exclude = [
    "recipes",
    "res",
    "misc",
    "2024",
    "hooks",
    "__pycache__"
]

[project.scripts]
grocery-shopper = "grocery_shopper.start:start"
